CREATE TABLE genders (
     id   SERIAL PRIMARY KEY,
     name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE countries (
   id   SERIAL PRIMARY KEY,
   name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE members (
     id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
     gender_id      INTEGER REFERENCES genders(id),
     country_id     INTEGER REFERENCES countries(id),
     name           VARCHAR(100) NOT NULL,
     surname        VARCHAR(100) NOT NULL,
     second_surname VARCHAR(100) NOT NULL DEFAULT '',
     email          VARCHAR(255) NOT NULL,
     birthdate      DATE,
     phone          VARCHAR(30) NOT NULL DEFAULT '',
     notes          TEXT NOT NULL DEFAULT '',
     created_at     TIMESTAMP NOT NULL DEFAULT now(),
     updated_at     TIMESTAMP NOT NULL DEFAULT now()
);

-- Insert genders (Spanish)
INSERT INTO genders (name) VALUES
    ('Masculino'),
    ('Femenino'),
    ('Otro');

-- Insert countries (Spanish)
INSERT INTO countries (name) VALUES
    ('Afganistán'),
    ('Albania'),
    ('Alemania'),
    ('Andorra'),
    ('Angola'),
    ('Antigua y Barbuda'),
    ('Arabia Saudita'),
    ('Argelia'),
    ('Argentina'),
    ('Armenia'),
    ('Australia'),
    ('Austria'),
    ('Azerbaiyán'),
    ('Bahamas'),
    ('Bangladés'),
    ('Barbados'),
    ('Baréin'),
    ('Bélgica'),
    ('Belice'),
    ('Benín'),
    ('Bielorrusia'),
    ('Birmania'),
    ('Bolivia'),
    ('Bosnia y Herzegovina'),
    ('Botsuana'),
    ('Brasil'),
    ('Brunéi'),
    ('Bulgaria'),
    ('Burkina Faso'),
    ('Burundi'),
    ('Bután'),
    ('Cabo Verde'),
    ('Camboya'),
    ('Camerún'),
    ('Canadá'),
    ('Catar'),
    ('Chad'),
    ('Chile'),
    ('China'),
    ('Chipre'),
    ('Ciudad del Vaticano'),
    ('Colombia'),
    ('Comoras'),
    ('Corea del Norte'),
    ('Corea del Sur'),
    ('Costa de Marfil'),
    ('Costa Rica'),
    ('Croacia'),
    ('Cuba'),
    ('Dinamarca'),
    ('Dominica'),
    ('Ecuador'),
    ('Egipto'),
    ('El Salvador'),
    ('Emiratos Árabes Unidos'),
    ('Eritrea'),
    ('Eslovaquia'),
    ('Eslovenia'),
    ('España'),
    ('Estados Unidos'),
    ('Estonia'),
    ('Esuatini'),
    ('Etiopía'),
    ('Filipinas'),
    ('Finlandia'),
    ('Fiyi'),
    ('Francia'),
    ('Gabón'),
    ('Gambia'),
    ('Georgia'),
    ('Ghana'),
    ('Granada'),
    ('Grecia'),
    ('Guatemala'),
    ('Guyana'),
    ('Guinea'),
    ('Guinea-Bisáu'),
    ('Guinea Ecuatorial'),
    ('Haití'),
    ('Honduras'),
    ('Hungría'),
    ('India'),
    ('Indonesia'),
    ('Irak'),
    ('Irán'),
    ('Irlanda'),
    ('Islandia'),
    ('Islas Marshall'),
    ('Islas Salomón'),
    ('Israel'),
    ('Italia'),
    ('Jamaica'),
    ('Japón'),
    ('Jordania'),
    ('Kazajistán'),
    ('Kenia'),
    ('Kirguistán'),
    ('Kiribati'),
    ('Kuwait'),
    ('Laos'),
    ('Lesoto'),
    ('Letonia'),
    ('Líbano'),
    ('Liberia'),
    ('Libia'),
    ('Liechtenstein'),
    ('Lituania'),
    ('Luxemburgo'),
    ('Madagascar'),
    ('Malasia'),
    ('Malaui'),
    ('Maldivas'),
    ('Malí'),
    ('Malta'),
    ('Marruecos'),
    ('Mauricio'),
    ('Mauritania'),
    ('México'),
    ('Micronesia'),
    ('Moldavia'),
    ('Mónaco'),
    ('Mongolia'),
    ('Montenegro'),
    ('Mozambique'),
    ('Namibia'),
    ('Nauru'),
    ('Nepal'),
    ('Nicaragua'),
    ('Níger'),
    ('Nigeria'),
    ('Noruega'),
    ('Nueva Zelanda'),
    ('Omán'),
    ('Países Bajos'),
    ('Pakistán'),
    ('Palaos'),
    ('Panamá'),
    ('Papúa Nueva Guinea'),
    ('Paraguay'),
    ('Perú'),
    ('Polonia'),
    ('Portugal'),
    ('Reino Unido'),
    ('República Centroafricana'),
    ('República Checa'),
    ('República del Congo'),
    ('República Democrática del Congo'),
    ('República Dominicana'),
    ('Ruanda'),
    ('Rumania'),
    ('Rusia'),
    ('Samoa'),
    ('San Cristóbal y Nieves'),
    ('San Marino'),
    ('San Vicente y las Granadinas'),
    ('Santa Lucía'),
    ('Santo Tomé y Príncipe'),
    ('Senegal'),
    ('Serbia'),
    ('Seychelles'),
    ('Sierra Leona'),
    ('Singapur'),
    ('Siria'),
    ('Somalia'),
    ('Sri Lanka'),
    ('Sudáfrica'),
    ('Sudán'),
    ('Sudán del Sur'),
    ('Suecia'),
    ('Suiza'),
    ('Surinam'),
    ('Tailandia'),
    ('Taiwán'),
    ('Tanzania'),
    ('Tayikistán'),
    ('Timor Oriental'),
    ('Togo'),
    ('Tonga'),
    ('Trinidad y Tobago'),
    ('Túnez'),
    ('Turkmenistán'),
    ('Turquía'),
    ('Tuvalu'),
    ('Ucrania'),
    ('Uganda'),
    ('Uruguay'),
    ('Uzbekistán'),
    ('Vanuatu'),
    ('Venezuela'),
    ('Vietnam'),
    ('Yemen'),
    ('Yibuti'),
    ('Zambia'),
    ('Zimbabue');